export default {
    owner: "owner",
    dev: "developer",
    admin: "admin",
    approver: "approver",
    donator: "donator",
    translator: "translator",
    extensions: "extension_developer",
    bugreport: "vulnerability_report",
    featured: "featured_creator",
    studio: "large_studio",
    votes: "votes_many",
    likes: "likes_many",
    followers: "followers_many",
    amongus: "sussy",
};