class DonatorCustomization {
    static FontSelection = {
        "Helvetica": "Helvetica Neue",
        "Arial": "Arial",
        "Verdana": "Verdana",
        "Tahoma": "Tahoma",
        "Times New Roman": "Times New Roman",
        "Georgia": "Georgia",
        "Sans Serif": "Open Sans",
        "Handwriting": "Handwriting",
        "Marker": "Marker",
        "Curly": "Curly",
        "Pixel": "Pixel",
        "Playful": "Playful",
        "Bubbly": "Bubbly",
        "Arcade": "Press Start 2P",
        "Archivo": "Archivo",
        "Archivo Black": "Archivo Black",
        "Oswald": "Oswald",
        "Raleway": "Raleway",
        "Nunito": "Nunito",
        "Rubik": "Rubik",
        "DM Sans": "DM Sans",
        "DynaPuff": "DynaPuff",
        "Anton": "Anton",
        "Prompt": "Prompt",
        "Lobster": "Lobster",
        "Permanent Marker": "Permanent Marker",
        "Indie Flower": "Indie Flower",
        "Creepster": "Creepster",
        "Metal Mania": "Metal Mania",
        "Rubik Glitch": "Rubik Glitch",
        "Ultra": "Ultra",
        "Silkscreen": "Silkscreen",
        "DotGothic16": "DotGothic16",
        "Geo": "Geo",
        "Fontdiner Swanky": "Fontdiner Swanky",
        "Sono": "Sono",
        "Unispace": "Unispace",
        "Eirian": "Eirian",
    };
    static DownloadOnlyFonts = {
        "Open Sans": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Open%20Sans"},
        "Curly": {"type": "file", "url": "/fonts/ofl/Griffy-Regular.ttf"},
        "Handwriting": {"type": "file", "url": "/fonts/ofl/handlee-regular.ttf"},
        "Marker": {"type": "file", "url": "/fonts/ofl/Knewave.ttf"},
        "Pixel": {"type": "file", "url": "/fonts/ofl/Grand9K-Pixel.ttf"},
        "Playful": {"type": "file", "url": "/fonts/ofl/BadComic-Regular.ttf"},
        "Bubbly": {"type": "file", "url": "/fonts/ofl/QTKooper.otf"},
        "Press Start 2P": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Press%20Start%202P"},
        "Archivo": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Archivo"},
        "Archivo Black": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Archivo%20Black"},
        "Oswald": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Oswald"},
        "Raleway": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Raleway"},
        "Nunito": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Nunito"},
        "Rubik": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Rubik"},
        "DM Sans": {"type": "css", "url": "https://fonts.googleapis.com/css?family=DM%20Sans"},
        "DynaPuff": {"type": "css", "url": "https://fonts.googleapis.com/css?family=DynaPuff"},
        "Anton": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Anton"},
        "Prompt": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Prompt"},
        "Lobster": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Lobster"},
        "Permanent Marker": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Permanent%20Marker"},
        "Indie Flower": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Indie%20Flower"},
        "Creepster": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Creepster"},
        "Metal Mania": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Metal%20Mania"},
        "Rubik Glitch": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Rubik%20Glitch"},
        "Ultra": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Ultra"},
        "Silkscreen": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Silkscreen"},
        "DotGothic16": {"type": "css", "url": "https://fonts.googleapis.com/css?family=DotGothic16"},
        "Geo": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Geo"},
        "Fontdiner Swanky": {"type": "css", "url": "https://fonts.googleapis.com/css?family=Fontdiner%20Swanky"},
        "Sono": {"type": "file", "url": "/fonts/ofl/Sono-Medium.woff2"},
        "Unispace": {"type": "file", "url": "/fonts/ofl/UnispaceRg.otf"},
        "Eirian": {"type": "file", "url": "/fonts/ofl/Eirian-Regular.ttf"},
    };
}

export default DonatorCustomization;